baseURL = "https://community.mahti.org/"

DefaultContentLanguage = "fi"
languageCode = "fi-fi"

theme = "hybrid"

[languages]
  [languages.fi]
    title = "Kontulan Kommuuni"
    weight = 1
  [languages.en]
    title = "Community of Kontula"
    weight = 2


